# -*- coding: utf-8 -*-
"""HelloWorld.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qhe2dVrF0C59S3C9w7k9pvgjKOQItOsY
"""

print("Hello World")